### ISSUE TITLE
Question about polybar

### ISSUE THREAD

**Issue by ThatOneCalculator** [Barbarossa93/Forester#1]
How did you get the double borders to work on your polybar? I can't seem to get it to work on my config.
![image](https://user-images.githubusercontent.com/44733677/116797447-99fb4980-aa9a-11eb-8ffd-6a4137dbd8f2.png)

**Comment by Barbarossa93** [comment]
Hey there. I actually have two bars running; one with a border and all of the content, and one slightly larger behind it to give the illusion of double borders. I also had to add some picom rules to prevent shadows on the bottom bar. Check my polybar launch script as well as the polybar config.

**Comment by ThatOneCalculator** [comment]
Interesting! I'll give it a shot and lyk how it goes. It shouldn't affect ram usage too much, right?

**Comment by Barbarossa93** [comment]
No, ram shouldn't be too much more. The second bar only has a space and therefore shouldn't use much. You could probably use lemonbar to create the second bar, I'm pretty sure that's much lighter in terms of resources, but I'd be surprised if it was much. I'm gonna go ahead and assume you got this figured out and I'll close this. If not, feel free to reopen.
